name: Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Copy file via scp
        uses: appleboy/scp-action@master
        env:
          HOST: "138.68.152.3"
          USERNAME: "root"
          PORT: "22"
          PASSWORD: "O9b21Tv^i!in"
        with:
          source: "./target/market-service-0.0.1-SNAPSHOT.jar"
          target: "/tmp/market"

      - name: Restart supervisor
        uses: appleboy/ssh-action@master
        with:
          HOST: "138.68.152.3"
          USERNAME: "root"
          PORT: "22"
          PASSWORD: "O9b21Tv^i!in"
          script: |
            mv /tmp/market/target/market-service-0.0.1-SNAPSHOT.jar  /opt/market-service/market-service-0.0.1-SNAPSHOT.jar
            supervisorctl restart all

