name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install postgres
        uses: harmon758/postgresql-action@v1
        with:
            postgresql version: '11'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify